config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :users, :skip => :registrations
  resources :etemplates

  root 'pages#home'
  get 'etemplates' => 'etemplates#index'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :trackable, :timeoutable, :lockable
end

app/models/etemplate.rb
class Etemplate < ActiveRecord::Base
  belongs_to :user
  has_attached_file :image, :styles => { :medium => '300x300', :thumb => '100x100' }
  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :etemplates
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/etemplates_controller.rb
class EtemplatesController < ApplicationController
  before_action :set_etemplate, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /etemplates
  # GET /etemplates.json
  def index
    @etemplates = Etemplate.all
  end

  # GET /etemplates/1
  # GET /etemplates/1.json
  def show
  end

  # GET /etemplates/new
  def new
    @etemplate = current_user.etemplates.build
  end

  # GET /etemplates/1/edit
  def edit
  end

  # POST /etemplates
  # POST /etemplates.json
  def create
    @etemplate = current_user.etemplates.build(etemplate_params)

    respond_to do |format|
      if @etemplate.save
        format.html { redirect_to etemplates_path }
        flash[:notice] = "Template successfully created."
        format.json { render :show, status: :created, location: @etemplate }
      else
        format.html { render :new }
        format.json { render json: @etemplate.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /etemplates/1
  # PATCH/PUT /etemplates/1.json
  def update
    respond_to do |format|
      if @etemplate.update(etemplate_params)
        format.html { redirect_to etemplates_path, notice: 'Template was successfully updated.' }
        format.json { render :show, status: :ok, location: @etemplate }
      else
        format.html { render :edit }
        format.json { render json: @etemplate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /etemplates/1
  # DELETE /etemplates/1.json
  def destroy
    @etemplate.destroy
    respond_to do |format|
      format.html { redirect_to etemplates_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_etemplate
      @etemplate = Etemplate.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def etemplate_params
      params[:etemplate].permit(:description, :image, :name, :codepen_data)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/etemplates_helper.rb
module EtemplatesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/etemplates/_form.html.erb
<%= form_for @etemplate, :html => { :multipart => true } do |f| %>
  <% if @etemplate.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@etemplate.errors.count, "error") %> prohibited this etemplate from being saved:</h2>

      <ul>
      <% @etemplate.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="jumbotron jumbo-clear jumbo-form text-center vertical-center">
    <div class="container">
      <h1>Create or Edit</h1>
      <form role="form">
        <div class="form-group">
          <div class="input-group">
            <span class="input-group-btn upload-btn-clear">
              <span class="btn btn-file">Upload an image<%= f.file_field :image, class: "form-control" %></span>
            </span>
            <%= f.text_field :name, :value => '', class: "form-control", :class => "file-upload-field", readonly: true %>
          </div>
        </div>
        <div class="form-group">
          <%= f.text_field :name, class: "form-control", :class => "input-field", :placeholder => "Name" %>
        </div>
        <div class="form-group">
          <%= f.text_field :description, class: "form-control", :class => "input-field", :placeholder => "Description" %>
        </div>
        <div class="form-group">
          <%= f.text_field :codepen_data, class: "form-control", :class => "input-field", :placeholder => "CodePen snippet" %>
        </div>
        <div class="form-group">
          <%= f.submit 'OK', class: "btn btn-clear" %>
          <%= link_to 'Cancel', etemplates_path, :class => "btn btn-link" %>
        </div>
      </form>
    </div>
  </div>
<% end %>

app/views/etemplates/edit.html.erb
<% @bg_url = '../../images/home-bg5.jpg' %>
<%= render 'layouts/bg_img' %>

<%= render 'form' %>

app/views/etemplates/index.html.erb
<% @bg_url = '../images/home-bg3.jpg' %>
<%= render 'layouts/bg_img' %>

<div id="template-container" class="transitions-enabled">
  <% @etemplates.each do |etemplate| %>
    <div class="template-thumb panel panel-default">
      <%= link_to image_tag(etemplate.image.url(:original)), etemplate %>

        <% if current_user.try(:admin?) %>
        <div class="panel-body">
          <div class="actions">
            <%= link_to '<span class="glyphicon glyphicon-pencil"></span>'.html_safe, edit_etemplate_path(etemplate) %>
            &nbsp;|&nbsp;
            <%= link_to '<span class="glyphicon glyphicon-trash"></span>'.html_safe, etemplate, method: :delete, data: {confirm: 'Really delete?'} %>
          </div>
        </div>
        <% end %>
    </div>
  <% end %>
</div>

app/views/etemplates/new.html.erb
<% @bg_url = '../images/home-bg5.jpg' %>
<%= render 'layouts/bg_img' %>

<%= render 'form' %>

app/views/etemplates/show.html.erb
<% @bg_url = '../images/home-bg4.jpg' %>
<%= render 'layouts/bg_img' %>

  <div class="row">
    <div class="col-md-offset-2 col-md-8">
      <div class="panel panel-default">
        <div class="panel-heading center">
          <%= raw @etemplate.codepen_data %>
        </div>
        <div class="panel-body">
          <h3><%= @etemplate.name %></h3>
          <p><%= @etemplate.description %></p>

          <% if current_user.try(:admin?) %>
            <%= link_to '<span class="glyphicon glyphicon-pencil"></span>'.html_safe, edit_etemplate_path(@etemplate) %>
            &nbsp;|&nbsp;
          <% end %>
          <%= link_to 'Back to Gallery', etemplates_path %>

        </div>
      </div>
    </div>
  </div>

app/views/layouts/_bg_img.html.erb
<style>
  body {
    margin-bottom: 60px;
    background: url('<%= @bg_url %>') no-repeat center center fixed;
    -webkit-background-size: cover;
    -moz-background-size: cover;
    -ms-background-size: cover;
    -o-background-size: cover;
    background-size: cover;
  }
</style>

app/views/layouts/_flashMessages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div id="flash-outer" class="navbar-fixed-top">
      <div class="container-fluid alert alert-<%=name.to_s == 'notice' ? 'success' : 'danger' %>"
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      </div>
    </div>
  <% end %>
<% end %>

app/views/layouts/_footer.html.erb
<div class="footer">
  <div class="container-fluid">
    <div class="left">&copy; <%= Time.now.year  %> DRC Dev Team</div>
    <div class="right">
      <a href="https://www.facebook.com/groups/DRC.DevTeam/">Facebook</a> |
      <a href="https://twitter.com/DRC_DevTeam">Twitter</a> |
      <a href="https://github.com/DRCdevteam">GitHub</a> |
      <a href="http://codepen.io/DRC-DevTeam/">Codepen</a>
    </div>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-inverse navbar-static-top" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#collapsed-navbar-content">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "DRC Digital", root_path, class:'navbar-brand' %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="collapsed-navbar-content">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Gallery", etemplates_path %></li>
        <% if current_user.try(:admin?) %>
          <li>
          <%= link_to 'Add Template', new_etemplate_path %>
          </li>
          <li>
          <%= link_to 'Sign Out', destroy_user_session_path, method: :delete %>
          </li>
        <% else %>
          <li>
          <%= link_to 'Sign In', new_user_session_path %>
          </li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_titlebar.html.erb
<div class="titlebar container"><h1><%= @titlebar %></h1></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Stealth Mode</title>
  <%= favicon_link_tag '../images/favicon.ico' %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
</head>
<body>

<!--==Navbar==-->
<%= render 'layouts/navbar' %>
<%= render 'layouts/flashMessages' %>

<div class="container">
  <div class="row-fluid">
    <%= yield %>
  </div>
</div>

<%= render 'layouts/footer' %>

</body>
</html>

app/views/pages/home.html.erb
<% @bg_url = '../images/home-bg1.jpg' %>
<%= render 'layouts/bg_img' %>

<div class="jumbotron jumbo-clear text-center vertical-center">
  <div class="container">
    <h1>DRC Digital</h1>
    <p>A collection of responsive, (mostly) bulletproof, custom designed and tested emails from the DRC&nbsp;Dev&nbsp;Team.</p>
    <%= link_to 'View the Gallery', etemplates_path, :class => "btn btn-clear" %>
  </div>
</div>